name = "Berayon Friends 26.2"
author = "berayon"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bf885003f6469da57d5e7472c5be4fb08953e7dd37ea13849a0388695d7e4ad"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
