name = "Berayon Friends 26.2"
author = "berayon"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c54ce9995865f32829c1b8cfe9757e2f8cee5dca366bf08e3f5453d8ff37f338"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
